name: Run and commit changes

on:
  push:
    paths:
      - 'cpp.json'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Setup Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'

    - name: Delete cpp_description.md
      run: |
        rm -f cpp_description.md

    - name: Run script
      run: |
        python3 src/description.py cpp.json

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Update cpp_description.md"
        commit_options: "--no-verify --signoff"
        file_pattern: cpp_description.md
